name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: win_x64, os: windows-latest, runtime: win-x64, executable: AssetRipper.CLI.Free.exe }
          #- { name: win_arm64, os: windows-latest, runtime: win-arm64, executable: AssetRipper.CLI.Free.exe }
          - { name: linux_x64, os: ubuntu-22.04, runtime: linux-x64, executable: AssetRipper.CLI.Free }
          #- { name: linux_arm64, os: ubuntu-22.04, runtime: linux-arm64, executable: AssetRipper.CLI.Free }
          #- { name: mac_x64, os: macos-latest, runtime: osx-x64, executable: AssetRipper.CLI.Free }
          #- { name: mac_arm64, os: macos-latest, runtime: osx-arm64, executable: AssetRipper.CLI.Free }

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.config.runtime }}
        working-directory: ./Source/AssetRipper.CLI.Free/

      - name: List Files
        shell: bash
        run: ls -R ./Source/0Bins/AssetRipper.CLI.Free/Release/

      - name: List Files
        shell: bash
        run: date -u > ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/compile_time.txt

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: AssetRipper_${{ matrix.config.name }}
          path: |
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/${{ matrix.config.executable }}
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/*.dll
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/*.so
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/*.dylib
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/compile_time.txt
          if-no-files-found: error
          
      - name: Generate Release Data
        shell: bash
        run: |
          export LC_ALL=en_US.utf8
          GIT_COMMIT_ID=$(echo "${{ github.sha }}" |  cut -c 1-7)
          UPDATE_TIME=$(echo ${{ github.event.repository.updated_at }} | sed 's/[:-]//g')
          echo "tag_name=v${UPDATE_TIME}" >> $GITHUB_ENV
          echo "release_name=${UPDATE_TIME} (${GIT_COMMIT_ID})" >> $GITHUB_ENV

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.release_name }}
          tag_name: ${{ env.tag_name }}
          generate_release_notes: true
          overwrite_files: false
          files: |
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/${{ matrix.config.executable }}
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/*.dll
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/*.so
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/*.dylib
            ./Source/0Bins/AssetRipper.CLI.Free/Release/${{ matrix.config.runtime }}/publish/compile_time.txt
